version: '3.9'
services:
  testserver:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server

    networks:
      - caddy
      
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app


  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client

    networks:
      - caddy
    volumes:
      - ./client/src:/app/src
    depends_on:
      - testserver
      
    labels:
      caddy: test.tedstar25.homes 
      caddy.reverse_proxy: "{{upstreams 80}}"






networks:
  caddy:
    external: true